### ISSUE TITLE
add check for underscores and uppercase letters

### ISSUE THREAD

**Issue by IPvSean** [network-automation/linklight#2]
>On March 1, 2018, we are updating our naming conventions for S3 buckets in the US East (N. Virginia) Region to match the naming conventions we use in all other worldwide AWS Regions. After this date, Amazon S3 will no longer support creating bucket names that contain uppercase letters or underscores.

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by IPvSean** [comment]
added check->
```
    - name: check for underscores
      fail:
        msg: "Amazon AWS does not allow underscores _ for s3 websites, please see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html"
      when:
        - create_login_page is defined
        - create_login_page
        - "'_' in ec2_name_prefix"
```
