### ISSUE TITLE
Ansible RPM should not be hardcoded to allow for patched/upgraded Ansible installs

### ISSUE THREAD

**Issue by termlen0** [network-automation/linklight#37]
In roles/control_node/tasks/main.yml, the following task downloads a hardcoded version of Ansible:

```
- name: Download Ansible
  get_url:
    url: http://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.5.0-1.el7.ans.noarch.rpm
    dest: /tmp/ansible.rpm
```

Bugs like https://github.com/ansible/ansible/issues/40064 have been resolved in newer versions of Ansible.

To enable the user to demo linklight using the appropriately patched version of Ansible, it will be great if the rpm file above is made into a variable and a sane default is set in the role's default/main.yml. Perhaps: `ansible-2.5.5-1.el7.ans.noarch.rpm `
